Repository hmcc-global/ripple-out-worship, pull requests merged in 2024-07, with the labels that each got.

#65 GH-64: bugs fixes
  ui/src/components/song/SongCard.tsx
  ui/src/components/song/SongListContainer.tsx
  ui/src/components/songsView/SongsButtonsCard.tsx
  ui/src/components/songsView/SongsInfoCard.tsx
  ui/src/components/songsView/SongsLyrics.tsx
  ui/src/components/songsView/SongsViewContainer.tsx
  ui/src/constants.ts
  ui/src/helpers/song/getLyricsNoChords.tsx
  ui/src/helpers/song/getLyricsPreview.tsx
  ui/src/helpers/song/index.tsx
  ui/src/types/song.types.ts
Labels: bug

#72 71 make songs setlists folders global
  ui/src/App.tsx
  ui/src/components/custom/CustomAppContainer.tsx
  ui/src/components/setlist/SetlistEditorContainer.tsx
  ui/src/components/setlist/SetlistFolderDrawer.tsx
  ui/src/components/setlist/SetlistListContainer.tsx
  ui/src/helpers/customHooks.ts
  ui/src/helpers/global/getFoldersGlobal.tsx
  ui/src/helpers/global/getSetlistsGlobal.tsx
  ui/src/helpers/global/getSongsGlobal.tsx
  ui/src/helpers/global/index.tsx
  ui/src/reducers/folderSlice.ts
  ui/src/reducers/index.tsx
  ui/src/reducers/setlistSlice.ts
  ui/src/reducers/songSlice.ts
  ui/src/store.ts
Labels: feat

#67 66 setlist view page
  server/src/controllers/setlist.controllers.ts
  server/src/models/setlist.model.ts
  server/src/types/setlist.types.ts
  ui/src/App.tsx
  ui/src/components/setlistView/SetlistViewContainer.tsx
  ui/src/components/setlistView/SetlistViewMenu.tsx
  ui/src/components/setlistView/SetlistViewPaper.tsx
  ui/src/components/song/SongCard.tsx
  ui/src/components/songsView/SongsButtonsCard.tsx
  ui/src/routes.ts
  ui/src/styles.css
  ui/src/theme.ts
  ui/src/types/setlist.types.ts
Labels: feat

#70 GH-63: Global Search Modal, Song Page Bug Fixes, UI Tweaks
  ui/src/App.tsx
  ui/src/components/custom/PrivateRouteWrapper.tsx
  ui/src/components/home/HomeContainer.tsx
  ui/src/components/home/HomeTab.tsx
  ui/src/components/home/RecommendedSongCard.tsx
  ui/src/components/navigation/GlobalSearchModal.tsx
  ui/src/components/navigation/NavigationPaper.tsx
  ui/src/components/navigation/PageHeader.tsx
  ui/src/components/navigation/Sidebar.tsx
  ui/src/components/navigation/searchModalComponents/RadioCard.tsx
  ui/src/components/navigation/searchModalComponents/SetlistSearchResult.tsx
  ui/src/components/navigation/searchModalComponents/SongSearchResult.tsx
  ui/src/components/song/SongCard.tsx
  ui/src/components/song/SongListContainer.tsx
  ui/src/components/song/SongSearch.tsx
  ui/src/components/song/SongTagArray.tsx
  ui/src/constants.ts
  ui/src/helpers/song/getFirstLineLyrics.tsx
  ui/src/helpers/song/index.tsx
  ui/src/theme.ts
  ui/src/types/setlist.types.ts
  ui/src/types/song.types.ts
Labels: bug, feat
